# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  dev:
    cmds:
      - watchexec -rc -e go,mod -i .git -- go run .
  gen:
    cmds:
      - webrpc-gen -schema="example.ridl" -target=golang -pkg=api -server -out="./api/example.gen.go"
