# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  gen:
    cmds:
      - webrpc-gen -schema="api.ridl" -target=golang -pkg=api -server -out="./api/api.gen.go"
      - webrpc-gen -schema="api.ridl" -target=typescript -client -out="./client/src/api/api.gen.ts"
  go:
    cmds:
      - watchexec -rc -e go,mod -i .git -- go run .
  web:
    dir: "./client"
    cmds:
      - pnpm dev
  desktop:
    dir: "./client"
    cmds:
      - pnpm tauri dev -r cargo-zigbuild # Use cargo-zigbuild for Zig linker
  android:
    dir: "./client"
    cmds:
      - pnpm tauri android dev
  devWeb:
    cmds:
      - task -p go web # parallel tasks
  devDesktop:
    cmds:
      - task -p go desktop # parallel tasks
  devAndroid:
    cmds:
      - task -p go android # parallel tasks
